# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2026-08-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='editor',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portadas'),
        ),
    ]
