# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2026-08-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20260821_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='apelildos',
            new_name='apellidos',
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
    ]
